name: Deploy Sphinx documentation to Pages

on:
push:
    branches: [master] # branch to trigger deployment

jobs:
pages:
    runs-on: ubuntu-20.04
    environment:
    name: github-pages
    url: ${{ steps.deployment.outputs.page_url }}
    permissions:
    pages: write
    id-token: write
    steps:
    - name: Install dependencies
      run: |
        pip install sphinx pydata-sphinx-theme myst_parser
    - id: deployment
    uses: sphinx-notes/pages@v3